use_frameworks!

platform :ios, '9.0'

target 'FYFSwfitDefines_Example' do
  pod 'FYFSwfitDefines', :path => '../'

  target 'FYFSwfitDefines_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
